GlobalParameters:
  MinimumRequiredVersion: 3.0.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 2
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: True
  SleepPercent: 200

BenchmarkProblems:

  ########################################
  # NN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 8 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M,N < VW
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 4 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [64] ]
          - Range: [ [1], [64], [1], [64] ]
          - Range: [ [64], [1], [1], [64] ]

  ########################################
  # NT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 8 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M,N < VW
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 4 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [64] ]
          - Range: [ [1], [64], [1], [64] ]
          - Range: [ [64], [1], [1], [64] ]

  ########################################
  # TN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 8 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M,N < VW
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 4 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [64] ]
          - Range: [ [1], [64], [1], [64] ]
          - Range: [ [64], [1], [1], [64] ]

  ########################################
  # TT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 8 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [64], [64], [1], [64] ]

    - # BenchmarkProblemSizeGroup - M,N < VW
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [True]
        - VectorWidth: [-1]
      ForkParameters:
        - ThreadTile:
          - [ 4, 4 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
        - DepthU: [ 4 ]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1], [1], [1], [64] ]
          - Range: [ [1], [64], [1], [64] ]
          - Range: [ [64], [1], [1], [64] ]

LibraryLogic:

LibraryClient:
